### ISSUE TITLE
Exception has occured: AttributeError

### ISSUE THREAD

**Issue by bkcproject086** [dazedanon/DazedMTLTool#10]
![Screenshot (53)](https://github.com/dazedanon/DazedMTLTool/assets/134508941/639878a0-ec90-4675-a443-47a9fd9e58cb)

Hi sir, I am having a problem
when running run.py, I encountered problems in the rgpmakermvmz.py section

Please help me, sir

**Comment by dazedanon** [comment]
You don't have a `.env` file in your project folder. You'll need it to run stuff. If you filled out `env.example` make sure you rename it.

**Comment by bkcproject086** [comment]
![Screenshot (53)](https://github.com/dazedanon/DazedMTLTool/assets/134508941/2aa64aad-b1cb-4f56-879d-d75d62ef258b)
I've changed the `.env` name files, however

I'm having a new problem, I don't really understand vscode

**Comment by Kryomancer** [comment]
You need to replace *all* the `<PLACEHOLDER_VALUES>` in the .env file. For example, this is caused by your .env file containing

```
threads="<NUMBER_OF_THREADS_PER_FILE>"
```

Whereas you need to fill in some value, for example if you wanted to have one thread per file:

```
threads="1"
```

**Comment by bkcproject086** [comment]
> You need to replace _all_ the `<PLACEHOLDER_VALUES>` in the .env file. For example, this is caused by your .env file containing
> 
> ```
> threads="<NUMBER_OF_THREADS_PER_FILE>"
> ```
> 
> Whereas you need to fill in some value, for example if you wanted to have one thread per file:
> 
> ```
> threads="1"
> ```

![Screenshot (59)](https://github.com/dazedanon/DazedMTLTool/assets/134508941/8adc9041-0e8d-4338-919a-1ee2a3d00829)

I have tried what you ordered,
I tried to translate the game from RPGM MV, but the problem appeared again

I'm sorry, I bothered you

**Comment by Kryomancer** [comment]
You can change the line 204 it highlights when giving that error from

```
tqdm.write(totalCost)
```
to
```
tqdm.write(str(totalCost))
```
To avoid this specific exception, though if the translationg/estimation worked as expected the chose module *should* have set it to a string to begin with. This may happen for example if the script can't find any files to translate: Make sure you have your game's `www/data/*.json` files in the `files` folder next to where the `start.py` script is.

(I snuck a fix for the string exception in with my main.py refactors on the `rework-translation-system` branch yesterday but it's not on `master` yet. It prevents the exception but if `totalCost` is not a string it's almost certainly just `0` which isn't that helpful either...)
