### ISSUE TITLE
How i can use using local openia?

### ISSUE THREAD

**Issue by mario6714** [dazedanon/DazedMTLTool#15]
I try to use this "https://github.com/oobabooga/text-generation-webui" but always the program try to connect to openia, any help? thanks

**Comment by dazedanon** [comment]
You can set it here in the .env.
![image](https://github.com/dazedanon/DazedMTLTool/assets/96628874/42186aa2-f437-44f0-9829-596d652104ac)

**Comment by m5kro** [comment]
> I try to use this "https://github.com/oobabooga/text-generation-webui" but always the program try to connect to openia, any help? thanks

Should be fixed in pull request #16
