### ISSUE TITLE
tl patch update script

### ISSUE THREAD

**Issue by m5kro** [dazedanon/DazedMTLTool#18]
Not sure if this is the right place to ask this but would you be willing to include the following script and text file in your future game uploads? It checks for new tl patches and applies them if found. You will only need to change the repo variable in patch-config.txt
[update-dazed-tl-patch.bat](https://pixeldrain.com/u/NbwCsh6B)
[patch-config.txt](https://pixeldrain.com/u/8qvGVbXf)

**Comment by dazedanon** [comment]
This is fantastic. I've been wanting to create something like this for a while but haven't had the motivation. I'll definitely include these in future patches.

Much appreciated, and I'll definitely credit you in the thread for it.
